/**
 * Deterministic safety layer. Runs BEFORE any model call, and its verdict can
 * only escalate — a model can never downgrade a matched urgent rule.
 *
 * Hard stops encoded here (from the build plan):
 *  - No reassurance when a message matches an urgent rule.
 *  - No dose or timing change generated by AI.
 *  - Uploaded text is data, never instructions.
 */

export type UrgentRuleInput = { id?: string; label: string; phrases: string; enabled?: boolean };

/**
 * Starter red-flag phrases for a fertility clinic. SAMPLE ONLY — a real
 * deployment ships the list the clinic's licensed clinicians approve, and the
 * clinic edits it from Settings.
 */
export const DEFAULT_URGENT_RULES: UrgentRuleInput[] = [
  {
    label: "Breathing difficulty",
    phrases:
      "short of breath|shortness of breath|can't breathe|cant breathe|cannot breathe|trouble breathing|hard to breathe|difficulty breathing|struggling to breathe",
  },
  { label: "Chest pain", phrases: "chest pain|chest hurts|pain in my chest|tight chest|chest tightness" },
  {
    label: "Severe abdominal pain",
    phrases:
      "severe stomach pain|severe abdominal pain|severe pain in my stomach|really bad stomach pain|extreme stomach pain|stomach pain is severe|unbearable pain|worst pain",
  },
  { label: "Fainting", phrases: "fainted|passed out|fainting|blacked out|about to faint" },
  { label: "Heavy bleeding", phrases: "heavy bleeding|bleeding heavily|soaking a pad|soaking through|lots of blood" },
  {
    label: "Rapid swelling / weight gain",
    phrases: "gained 2 pounds|gained two pounds|gained 1 kg|rapid weight gain|belly is very swollen|stomach very swollen|very bloated and",
  },
  {
    label: "Can't keep fluids down",
    phrases: "can't keep fluids down|cant keep fluids down|can't keep water down|vomiting all day|keep throwing up|nonstop vomiting",
  },
  { label: "Very little urine", phrases: "barely peeing|not peeing|very little urine|haven't urinated|dark urine and" },
  { label: "Leg pain / swelling", phrases: "calf pain|leg is swollen|swollen leg|pain in my calf" },
  {
    label: "Self-harm risk",
    phrases: "kill myself|end my life|suicidal|want to die|hurt myself|self harm|self-harm",
  },
];

export function normalize(text: string) {
  return text
    .toLowerCase()
    .replace(/[’‘`]/g, "'")
    .replace(/[^a-z0-9'\s-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export type UrgentMatch = { ruleId?: string; label: string; phrase: string };

export function matchUrgent(text: string, rules: UrgentRuleInput[]): UrgentMatch | null {
  const n = ` ${normalize(text)} `;
  for (const rule of rules) {
    if (rule.enabled === false) continue;
    for (const raw of rule.phrases.split("|")) {
      const phrase = normalize(raw);
      if (phrase && n.includes(` ${phrase}`)) return { ruleId: rule.id, label: rule.label, phrase: raw.trim() };
    }
  }
  return null;
}

/**
 * Questions that ask the assistant to move, skip, double or change a dose.
 * These never get a generated instruction: the answer is the clinic's own
 * missed-dose / timing guidance plus the on-call route.
 */
const MEDS = "gonal|gonal-f|menopur|cetrotide|ganirelix|ovidrel|trigger|lupron|follistim|progesterone|estradiol";

const TIMING_PATTERNS: RegExp[] = [
  /\b(take|do|give|inject)\b.{0,30}\b(late|later|early|earlier|tomorrow instead|in the morning instead)\b/,
  /\b(late|later|early|earlier)\b.{0,20}\b(dose|shot|injection|medication|meds)\b/,
  /\b(skip|skipped|miss|missed|forgot|forget)\b.{0,30}\b(dose|shot|injection|medication|meds|menopur|gonal|cetrotide|trigger)\b/,
  new RegExp(`\\b(double|extra|more|less|half|increase|decrease|lower|raise|reduce)\\b.{0,20}\\b(dose|shot|injection|units|iu|${MEDS})\\b`),
  /\bchange\b.{0,20}\b(dose|time|timing|schedule)\b/,
  /\b(stop|pause)\b.{0,15}\b(taking|my|the)\b.{0,20}\b(medication|meds|shots|injections|menopur|gonal|cetrotide)\b/,
  /\bhow late\b/,
  /\bmove\b.{0,20}\b(dose|shot|injection)\b/,
];

export function isTimingOrDoseChange(text: string) {
  const n = normalize(text);
  return TIMING_PATTERNS.some((re) => re.test(n));
}

/**
 * Prompt-injection screen for uploaded clinic documents. Flags are shown to
 * staff before approval; content is always passed to models inside a data
 * wrapper regardless.
 */
const INJECTION_PATTERNS: [RegExp, string][] = [
  [/ignore (all |any )?(previous|prior|above) (instructions|rules)/i, "Asks the model to ignore its instructions"],
  [/disregard (the |your )?(system|previous|safety)/i, "Asks the model to disregard safety rules"],
  [/you are now|act as (an?|the) /i, "Tries to reassign the assistant's role"],
  [/system prompt|developer message/i, "Mentions the system prompt"],
  [/(tell|advise) (the )?patients? to (double|skip|increase|stop)/i, "Instructs dose changes to patients"],
  [/do not (escalate|contact|call) (the )?(nurse|clinic|care team)/i, "Discourages escalation"],
  [/<\/?(script|system|instructions?)>/i, "Contains markup that looks like instructions"],
];

export function scanForInjection(text: string): string[] {
  const flags = new Set<string>();
  for (const [re, label] of INJECTION_PATTERNS) if (re.test(text)) flags.add(label);
  return [...flags];
}
